import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Horns & Halos | Duality Streetwear",
  description:
    "Streetwear forged between light and dark. AI-designed emblems on tees, hoodies, mugs and posters.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#050505] text-neutral-200 antialiased">
        <header className="border-b border-[#d4af3722]">
          <div className="mx-auto max-w-6xl px-6 py-6 text-center">
            <a href="/">
              <h1 className="text-2xl md:text-3xl font-light tracking-[0.35em] uppercase text-[#d4af37]">
                Horns &amp; Halos
              </h1>
              <p className="mt-1 text-[10px] md:text-[11px] tracking-[0.4em] uppercase text-neutral-500">
                Duality Studio — forged between light &amp; dark
              </p>
            </a>
          </div>
        </header>
        <main className="mx-auto max-w-6xl px-6 py-10">{children}</main>
        <footer className="border-t border-[#d4af3722] mt-16">
          <div className="mx-auto max-w-6xl px-6 py-8 text-center text-[11px] tracking-[0.25em] uppercase text-neutral-600">
            Horns &amp; Halos · every design generated by the HA.OS Product Line
          </div>
        </footer>
      </body>
    </html>
  );
}
