import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { readProducts, getProduct, productImage } from "@/lib/products";

export function generateStaticParams() {
  return readProducts().map((p) => ({ slug: p.slug }));
}

export function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Metadata {
  const p = getProduct(params.slug);
  if (!p) return {};
  return {
    title: p.seo_title ?? p.title,
    description: p.seo_description ?? p.description,
  };
}

export default function ProductPage({
  params,
}: {
  params: { slug: string };
}) {
  const p = getProduct(params.slug);
  if (!p) notFound();

  const images = (p.images ?? []).length ? p.images : ["mockup_tee.jpg"];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
      {/* gallery */}
      <div>
        <div className="aspect-square rounded-xl overflow-hidden border border-[#1d1d20] bg-black">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={productImage(p.slug, images[0])}
            alt={p.title}
            className="w-full h-full object-cover"
          />
        </div>
        <div className="grid grid-cols-4 gap-3 mt-3">
          {images.map((f) => (
            <a
              key={f}
              href={productImage(p.slug, f)}
              className="aspect-square rounded-lg overflow-hidden border border-[#1d1d20] hover:border-[#d4af3766]"
              title={f}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={productImage(p.slug, f)}
                alt={`${p.title} — ${f}`}
                className="w-full h-full object-cover"
              />
            </a>
          ))}
        </div>
        {p.design && (
          <div className="mt-3 flex items-center gap-3">
            <a
              href={productImage(p.slug, p.design)}
              className="h-20 w-20 rounded-lg overflow-hidden border border-[#1d1d20] hover:border-[#d4af3766]"
              title="Raw design (transparent PNG)"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={productImage(p.slug, p.design)}
                alt="design"
                className="w-full h-full object-cover bg-[#111]"
              />
            </a>
            <span className="text-[11px] text-neutral-500 uppercase tracking-wider">
              raw design · transparent PNG
            </span>
          </div>
        )}
      </div>

      {/* details */}
      <div>
        <a href="/" className="text-[11px] uppercase tracking-[0.25em] text-neutral-500 hover:text-[#d4af37]">
          ← Back to the collection
        </a>
        <h1 className="mt-3 text-2xl md:text-3xl font-light text-neutral-100">
          {p.title}
        </h1>
        <p className="mt-2 text-xl text-[#d4af37] font-semibold">
          ${p.price_usd.toFixed(2)}
        </p>
        <p className="mt-5 text-sm leading-relaxed text-neutral-400">
          {p.description}
        </p>

        <div className="mt-6 flex flex-wrap gap-2">
          {(p.tags ?? []).map((t) => (
            <span
              key={t}
              className="text-[10px] uppercase tracking-wider text-neutral-400 border border-[#26262a] rounded px-2 py-1"
            >
              {t}
            </span>
          ))}
        </div>

        <div className="mt-8 border-t border-[#1d1d20] pt-6 space-y-2 text-[12px] text-neutral-500">
          <p>· Printed on demand — tees, hoodies, mugs &amp; posters</p>
          <p>· Design generated by the Horns &amp; Halos AI line</p>
          {p.published_at && <p>· Forged {p.published_at.slice(0, 10)}</p>}
        </div>
      </div>
    </div>
  );
}
